name: CD

on:
  push:
    branches:
      - main

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ~/ponpub-client
            pm2 stop pm2-ecosystem.config.js
            git pull origin main
            git status
            yarn install
            yarn build
            pm2 restart pm2-ecosystem.config.js
